exclude: >
  (?x)^(
      sphinx/build/|
      sphinx/source/_static/html/
  )$
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
    -   id: double-quote-string-fixer
    -   id: name-tests-test
    -   id: requirements-txt-fixer
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.12.0
    hooks:
    -   id: reorder-python-imports
        exclude: ^(pre_commit/resources/|testing/resources/python3_hooks_repo/)
        args: [--py39-plus, --add-import, 'from __future__ import annotations']
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
    -   id: add-trailing-comma
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.14.0
    hooks:
    -   id: pyupgrade
        args: [--py39-plus]
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.292
    hooks:
    -   id: ruff
-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black
        args: [--target-version, 'py310']
# This hook is not working fine
# -   repo: https://github.com/pre-commit/mirrors-mypy
#     rev: v1.5.1
#     hooks:
#       - id: mypy
#         args: [--explicit-package-bases, 'src/']
-   repo: https://github.com/PyCQA/docformatter
    rev: v1.7.5
    hooks:
    -   id: docformatter
        additional_dependencies: [tomli]
        args: [--in-place, --config, pyproject.toml]
        language_version: python3.9
